# Generated by Django 5.2.17 on 2026-09-25 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0003_make_format_and_thematics_required"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        upload_to="news/images/", verbose_name="Image"
                    ),
                ),
                (
                    "alt_text_fr",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Alt text (FR)",
                    ),
                ),
                (
                    "alt_text_en",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Alt text (EN)",
                    ),
                ),
                (
                    "alt_text_de",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Alt text (DE)",
                    ),
                ),
                (
                    "alt_text_it",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        verbose_name="Alt text (IT)",
                    ),
                ),
                (
                    "caption_fr",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption (FR)"
                    ),
                ),
                (
                    "caption_en",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption (EN)"
                    ),
                ),
                (
                    "caption_de",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption (DE)"
                    ),
                ),
                (
                    "caption_it",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Caption (IT)"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Author"
                    ),
                ),
                (
                    "rights",
                    models.CharField(
                        blank=True, max_length=200, verbose_name="Rights"
                    ),
                ),
                (
                    "crop_left",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Crop left"
                    ),
                ),
                (
                    "crop_upper",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Crop upper"
                    ),
                ),
                (
                    "crop_right",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Crop right"
                    ),
                ),
                (
                    "crop_lower",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="Crop lower"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_images_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="news.news",
                        verbose_name="News",
                    ),
                ),
            ],
            options={
                "verbose_name": "News image",
                "verbose_name_plural": "News images",
                "ordering": ["-created_at"],
            },
        ),
    ]
