# Generated by Django 5.2.13 on 2026-07-14 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("block_types", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsFormat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_fr",
                    models.CharField(
                        help_text="Label in French",
                        max_length=200,
                        verbose_name="French",
                    ),
                ),
                (
                    "label_en",
                    models.CharField(
                        help_text="Label in English",
                        max_length=200,
                        verbose_name="English",
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        help_text="Label in German",
                        max_length=200,
                        verbose_name="German",
                    ),
                ),
                (
                    "label_it",
                    models.CharField(
                        help_text="Label in Italian",
                        max_length=200,
                        verbose_name="Italian",
                    ),
                ),
                (
                    "icon",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "allowed_blocks",
                    models.ManyToManyField(
                        blank=True,
                        related_name="news_formats",
                        to="block_types.blocktype",
                    ),
                ),
            ],
            options={
                "verbose_name": "News Format",
                "verbose_name_plural": "News Formats",
                "db_table": "news_formats",
            },
        ),
    ]
