export default {
  plugins: ['stylelint-order'],
  extends: ['stylelint-config-recommended-scss'],
  rules: {
    'order/order': [
      'custom-properties',
      'dollar-variables',
      'declarations',
      'rules',
    ],
    'order/properties-order': [
      'content',
      'display',
      'flex',
      'position',
      'top',
      'right',
      'bottom',
      'left',
      'float',
      'width',
      'height',
      'margin',
      'padding',
      'background',
      'border',
      'font-family',
      'font-size',
      'line-height',
      'font-weight',
      'font-style',
      'color',
      'transform',
      'transition',
    ],
  },
}
