opdo:
  urls:
    - https://itsaudit0016.xaas.epfl.ch:9200
    - https://itsaudit0017.xaas.epfl.ch:9200
    - https://itsaudit0018.xaas.epfl.ch:9200
  index: opdo
  api_key: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_actu/OPDo/OPDo_prod/secrets_OPDo.yml') | from_yaml).opdo.api_key }}"

certificate: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_actu/OPDo/OPDo_prod/OPDo_ca_production.crt') }}"
