opdo:
  urls:
    - https://itsaudit0025.xaas.epfl.ch:9200
    - https://itsaudit0026.xaas.epfl.ch:9200
  index: opdo-test
  api_key: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_actu/OPDo/OPDo_test/secrets_OPDo.yml') | from_yaml).opdo.api_key }}"

certificate: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_actu/OPDo/OPDo_test/OPDo_ca_test.crt') }}"
