# Generated by Django 5.2.13 on 2026-06-02 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Thematic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_fr",
                    models.CharField(
                        help_text="Label in French",
                        max_length=200,
                        verbose_name="French",
                    ),
                ),
                (
                    "label_en",
                    models.CharField(
                        help_text="Label in English",
                        max_length=200,
                        verbose_name="English",
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        help_text="Label in German",
                        max_length=200,
                        verbose_name="German",
                    ),
                ),
                (
                    "label_it",
                    models.CharField(
                        help_text="Label in Italian",
                        max_length=200,
                        verbose_name="Italian",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this thematic is active and visible in the system.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this thematic is displayed on the main menu.",
                        verbose_name="Main",
                    ),
                ),
                (
                    "has_homepage",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this thematic has a dedicated homepage.",
                        verbose_name="Has Homepage",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Defines the display order. A value of 0 means the thematic is hidden.",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Thematic",
                "verbose_name_plural": "Thematics",
            },
        ),
    ]
