# Generated by Django 5.2.13 on 2026-06-01 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Thematic",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("label_fr", models.CharField(max_length=200)),
                ("label_en", models.CharField(max_length=200)),
                ("label_de", models.CharField(max_length=200)),
                ("label_it", models.CharField(max_length=200)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this thematic is active and visible in the system.",
                        verbose_name="Active",
                    ),
                ),
                (
                    "is_main",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this thematic is displayed on the main page.",
                        verbose_name="Main",
                    ),
                ),
                (
                    "has_homepage",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether this thematic has a dedicated homepage.",
                        verbose_name="Has Homepage",
                    ),
                ),
                (
                    "order",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Defines the display order. A value of 0 means the thematic is hidden.",
                        verbose_name="Order",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
