# Generated by Django 5.2.13 on 2026-06-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("thematics", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="thematic",
            name="has_homepage",
        ),
    ]
