# Generated by Django 5.2.13 on 2026-06-19 09:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0002_remove_entity_has_homepage"),
        ("thematics", "0002_remove_thematic_has_homepage"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Homepage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="Define the Slug of this Homepage",
                        max_length=200,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "entity",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage",
                        to="entities.entity",
                        verbose_name="Entity",
                    ),
                ),
                (
                    "thematic",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="homepage",
                        to="thematics.thematic",
                        verbose_name="Thematic",
                    ),
                ),
                (
                    "users",
                    models.ManyToManyField(
                        blank=True,
                        related_name="homepages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Users",
                    ),
                ),
            ],
            options={
                "verbose_name": "Homepage",
                "verbose_name_plural": "Homepages",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("entity__isnull", False),
                                ("thematic__isnull", True),
                            ),
                            models.Q(
                                ("entity__isnull", True),
                                ("thematic__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="homepage_must_have_exactly_one_relation",
                    )
                ],
            },
        ),
    ]
