# Generated by Django 5.2.13 on 2026-06-11 12:54

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homepages", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="users",
            field=models.ManyToManyField(
                blank=True,
                related_name="homepages",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Users",
            ),
        ),
    ]
