# Generated by Django 5.2.13 on 2026-06-12 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "label_fr",
                    models.CharField(
                        help_text="Label in French",
                        max_length=200,
                        verbose_name="French",
                    ),
                ),
                (
                    "label_en",
                    models.CharField(
                        help_text="Label in English",
                        max_length=200,
                        verbose_name="English",
                    ),
                ),
                (
                    "label_de",
                    models.CharField(
                        help_text="Label in German",
                        max_length=200,
                        verbose_name="German",
                    ),
                ),
                (
                    "label_it",
                    models.CharField(
                        help_text="Label in Italian",
                        max_length=200,
                        verbose_name="Italian",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Language code (e.g. 'fr', 'en', 'de', 'it').",
                        max_length=2,
                        unique=True,
                        verbose_name="Code",
                    ),
                ),
            ],
            options={
                "verbose_name": "Language",
                "verbose_name_plural": "Languages",
                "ordering": ["code"],
            },
        ),
    ]
