# Web
- name: Images - Tag and push App to Quay
  community.docker.docker_image:
    name: "{{ app_image_source }}"
    repository: "{{ quay_host }}/{{ quay_repo_name }}/{{ app_image }}"
    push: true
    source: pull

# Nginx
- name: Images - Tag and push Nginx to Quay
  community.docker.docker_image:
    name: "{{ nginx_image_source }}"
    repository: "{{ quay_host }}/{{ quay_repo_name }}/{{ nginx_image }}"
    push: true
    source: pull
