- name: Pull and push images
  include_tasks:
    file: images.yml
    apply:
      tags:
        - common.image
  tags:
    - common.image

- name: Service accounts
  include_tasks:
    file: accounts.yml
    apply:
      tags:
        - common.accounts
  tags:
    - common.accounts

- name: Create Storage
  include_tasks:
    file: storage.yml
    apply:
      tags:
        - common.storage
  tags:
    - common.storage
