# Generated by Django 5.2.13 on 2026-06-12 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("entities", "0001_initial"),
        ("thematics", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="News",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Created at"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="news_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Created by",
                    ),
                ),
                (
                    "entities",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Entities related to this news.",
                        related_name="news",
                        to="entities.entity",
                        verbose_name="Entities",
                    ),
                ),
                (
                    "thematics",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Thematics related to this news.",
                        related_name="news",
                        to="thematics.thematic",
                        verbose_name="Thematics",
                    ),
                ),
            ],
            options={
                "verbose_name": "News",
                "verbose_name_plural": "News",
                "ordering": ["-created_at"],
            },
        ),
    ]
