# Generated by Django 5.2.13 on 2026-08-10 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0001_initial"),
        ("news_formats", "0002_populate_formats_and_blocks"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="format",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="news",
                to="news_formats.newsformat",
                verbose_name="Format",
            ),
        ),
    ]
