# Generated by Django 5.2.17 on 2026-10-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("news", "0003_make_format_and_thematics_required"),
    ]

    operations = [
        migrations.AddField(
            model_name="news",
            name="is_under_cc_license",
            field=models.BooleanField(default=False),
        ),
    ]
