all:
  hosts:
    svc0016d-actus:
      ansible_connection: local
      ansible_host: localhost
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
      openshift_namespace: svc0016d-actus
  vars:
    openshift_env: dev
    secrets: "{{ lookup('pipe', 'keybase fs read /keybase/team/epfl_actu/dev/secrets.yml') | from_yaml }}"
    app: actu

    # Images
    app_image_tag: "0.0.5"
    app_image: "actu:{{ app_image_tag }}"
    app_image_source: "ghcr.io/epfl-si/{{ app_image }}"
    nginx_image_tag: 1.30-alpine
    nginx_image: "nginx-unprivileged:{{ nginx_image_tag }}"
    nginx_image_source: "docker.io/nginxinc/{{ nginx_image }}"

    # Storage
    web_app_pv_size: "1Gi"  # 1Gi is symbolic. 60Gi in reality

    # NGINX/Routing
    run_environment: dev
    avi_route_access_level: private
    actu_hosts:
      - dev-ractu.epfl.ch
    nginx_real_ip_header: X-Forwarded-For

    # App
    django_email_backend: utils.mail.ToAdminEmailBackend
