# Generated by Django 5.2.17 on 2026-08-24 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0002_news_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsMultiRef",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("it", "Italian"),
                        ],
                        max_length=2,
                        null=True,
                        verbose_name="Language",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("link", "Link"),
                            ("file", "File"),
                            ("image", "Image"),
                        ],
                        max_length=20,
                        verbose_name="Type",
                    ),
                ),
                ("ref", models.CharField(max_length=512, verbose_name="Ref")),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="multirefs",
                        to="news.news",
                        verbose_name="News",
                    ),
                ),
            ],
            options={
                "verbose_name": "News multi-reference",
                "verbose_name_plural": "News multi-references",
            },
        ),
    ]
