"""
Django settings for configs project.

Generated by 'django-admin startproject' using Django 5.2.13.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from pathlib import Path

from django.utils.translation import gettext_lazy as _

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv("ACTU_SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv("ACTU_DEBUG_MODE", False)

# SECURITY WARNING: don't run with debug_toolbar turned on in production!
ACTU_SHOW_DEBUG_TOOLBAR = os.getenv("ACTU_SHOW_DEBUG_TOOLBAR", False)

ALLOWED_HOSTS = []

# A list of all the people who get error notifications.
ADMINS = [
    ("Actu Developers", "actu-developers@groupes.epfl.ch"),
]

EMAIL_BACKEND = os.getenv(
    "ACTU_DJANGO_EMAIL_BACKEND",
    "django.core.mail.backends.console.EmailBackend",
)
EMAIL_HOST = "mail.epfl.ch"
EMAIL_PORT = 25
EMAIL_TIMEOUT = 10
SERVER_EMAIL = "news-noreply@epfl.ch"


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    #
    # Packages
    "django_epfl_web2018",
    "django_filters",
    "django_vite",
    "drf_spectacular",
    "mozilla_django_oidc",
    "rest_framework",
    #
    # Applications
    "audit_log",
    "api",
    "block_types",
    "entities",
    "homepages",
    "news",
    "news_formats",
    "thematics",
    "translations",
    "users",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.locale.LocaleMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "audit_log.middleware.AuditUserMiddleware",
]

ROOT_URLCONF = "configs.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [
            BASE_DIR / "templates",
        ],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "thematics.context_processors.global_thematics",
                "entities.context_processors.footer_entities",
                "utils.context_processors.get_default_lang",
            ],
        },
    },
]

WSGI_APPLICATION = "configs.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "HOST": os.getenv("ACTU_DATABASE_HOST"),
        "PORT": os.getenv("ACTU_DATABASE_PORT"),
        "NAME": os.getenv("ACTU_DATABASE_NAME"),
        "USER": os.getenv("ACTU_DATABASE_USER"),
        "PASSWORD": os.getenv("ACTU_DATABASE_PASSWORD"),
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = []

AUTH_USER_MODEL = "users.User"

AUTHENTICATION_BACKENDS = ("django_epfl_entra_id.auth.EPFLOIDCAB",)

TENANT_ID = os.getenv("ACTU_TENANT_ID")

OIDC_RP_CLIENT_ID = os.getenv("ACTU_OIDC_RP_CLIENT_ID")
OIDC_RP_CLIENT_SECRET = os.getenv("ACTU_OIDC_RP_CLIENT_SECRET")

AUTH_DOMAIN = f"https://login.microsoftonline.com/{TENANT_ID}"
OIDC_OP_AUTHORIZATION_ENDPOINT = f"{AUTH_DOMAIN}/oauth2/v2.0/authorize"
OIDC_OP_TOKEN_ENDPOINT = f"{AUTH_DOMAIN}/oauth2/v2.0/token"
OIDC_OP_JWKS_ENDPOINT = f"{AUTH_DOMAIN}/discovery/v2.0/keys"
OIDC_OP_USER_ENDPOINT = "https://graph.microsoft.com/oidc/userinfo"
OIDC_RP_SIGN_ALGO = "RS256"
OIDC_REQUIRE_AUTHORIZATIONS = True

LOGIN_URL = "/auth/authenticate"
LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "/"
LOGIN_REDIRECT_URL_FAILURE = "/forbidden"

# Accred API (https://api.epfl.ch)
ACTU_API_RIGHT_ID = os.getenv("ACTU_API_RIGHT_ID")
ACTU_API_USERNAME = os.getenv("ACTU_API_USERNAME")
ACTU_API_PASSWORD = os.getenv("ACTU_API_PASSWORD")
ACTU_API_BASE_URL = "https://api.epfl.ch"

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en"

LANGUAGES = [
    ("en", _("English")),
    ("fr", _("French")),
    ("de", _("German")),
    ("it", _("Italian")),
]

LOCALE_PATHS = [
    BASE_DIR / "locale",
]

TIME_ZONE = "Europe/Zurich"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_ROOT = BASE_DIR / "static_root"

STATIC_URL = "static/"

DJANGO_VITE = {
    "default": {
        "dev_mode": DEBUG,
    }
}


# Django REST Framework
# https://www.django-rest-framework.org/

REST_FRAMEWORK = {
    "ALLOWED_VERSIONS": ["v1"],
    "DEFAULT_AUTHENTICATION_CLASSES": [
        "rest_framework.authentication.SessionAuthentication",
    ],
    "DEFAULT_FILTER_BACKENDS": [
        "django_filters.rest_framework.DjangoFilterBackend",
    ],
    "DEFAULT_PERMISSION_CLASSES": [
        "rest_framework.permissions.IsAuthenticated",
    ],
    "DEFAULT_PAGINATION_CLASS": (
        "rest_framework.pagination.PageNumberPagination"
    ),
    "DEFAULT_RENDERER_CLASSES": [
        "rest_framework.renderers.JSONRenderer",
        "rest_framework.renderers.BrowsableAPIRenderer",
    ],
    "DEFAULT_SCHEMA_CLASS": ("drf_spectacular.openapi.AutoSchema"),
    "DEFAULT_VERSION": "v1",
    "DEFAULT_VERSIONING_CLASS": (
        "rest_framework.versioning.URLPathVersioning"
    ),
    "PAGE_SIZE": 10,
}

SPECTACULAR_SETTINGS = {
    # Basic metadata
    "TITLE": _("Actu API"),
    "DESCRIPTION": _("API documentation for Actu."),
    "VERSION": "1.0.0",
    # Swagger UI behavior
    "SERVE_INCLUDE_SCHEMA": False,
    "SWAGGER_UI_FAVICON_HREF": "https://web2018.epfl.ch/logo/favicon.ico",
}


# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# Django Debug Toolbar
# https://django-debug-toolbar.readthedocs.io/en/latest/configuration.html

if DEBUG:
    INSTALLED_APPS += ("debug_toolbar",)
    MIDDLEWARE += ("debug_toolbar.middleware.DebugToolbarMiddleware",)


def show_debug_toolbar(request):
    return ACTU_SHOW_DEBUG_TOOLBAR


DEBUG_TOOLBAR_CONFIG = {
    "SHOW_TOOLBAR_CALLBACK": show_debug_toolbar,
}
