# Generated by Django 5.2.13 on 2026-08-13 14:59

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newstranslation",
            name="author",
            field=tinymce.models.HTMLField(default="", verbose_name="Author"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newstranslation",
            name="extract",
            field=tinymce.models.HTMLField(null=True, verbose_name="Extract"),
        ),
        migrations.AddField(
            model_name="newstranslation",
            name="funding",
            field=tinymce.models.HTMLField(null=True, verbose_name="Funding"),
        ),
        migrations.AddField(
            model_name="newstranslation",
            name="hat",
            field=tinymce.models.HTMLField(default="", verbose_name="Hat"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newstranslation",
            name="references",
            field=tinymce.models.HTMLField(
                null=True, verbose_name="References"
            ),
        ),
    ]
