# Generated by Django 5.2.13 on 2026-08-18 13:06

import django_editorjs_fields.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newstranslation",
            name="body",
            field=django_editorjs_fields.fields.EditorJsJSONField(
                blank=True, null=True
            ),
        ),
    ]
