# Generated by Django 5.2.13 on 2026-08-13 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("translations", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newstranslation",
            name="author",
            field=models.TextField(default="", verbose_name="Author"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newstranslation",
            name="extract",
            field=models.TextField(null=True, verbose_name="Extract"),
        ),
        migrations.AddField(
            model_name="newstranslation",
            name="funding",
            field=models.TextField(null=True, verbose_name="Funding"),
        ),
        migrations.AddField(
            model_name="newstranslation",
            name="hat",
            field=models.TextField(default="", verbose_name="Hat"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="newstranslation",
            name="references",
            field=models.TextField(null=True, verbose_name="References"),
        ),
    ]
