# Generated by Django 5.2.17 on 2026-08-19 09:26

import tinymce.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            "translations",
            "0002_newstranslation_author_newstranslation_extract_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="newstranslation",
            name="extract",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Extract"
            ),
        ),
        migrations.AlterField(
            model_name="newstranslation",
            name="funding",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="Funding"
            ),
        ),
        migrations.AlterField(
            model_name="newstranslation",
            name="references",
            field=tinymce.models.HTMLField(
                blank=True, null=True, verbose_name="References"
            ),
        ),
    ]
