# Generated by Django 5.2.13 on 2026-09-09 10:39

import autoslug.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "translations",
            "0002_newstranslation_author_newstranslation_extract_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="newstranslation",
            name="slug",
            field=autoslug.fields.AutoSlugField(
                always_update=True,
                blank=True,
                editable=False,
                max_length=255,
                null=True,
                populate_from="title",
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="NewsSlugHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "old_slug",
                    models.CharField(
                        db_index=True, max_length=255, unique=True
                    ),
                ),
                (
                    "news_translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_slugs",
                        to="translations.newstranslation",
                    ),
                ),
            ],
        ),
    ]
