# Generated by Django 5.2.13 on 2026-08-24 14:07

from django.db import migrations

import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
        ("audit_log", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", users.models.AuditUserManager()),
            ],
        ),
    ]
