# Generated by Django 5.2.17 on 2026-09-22 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("translations", "0003_newstranslation_slug_newsslughistory"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("url", models.URLField(max_length=512, verbose_name="URL")),
                (
                    "translation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="urls",
                        to="translations.newstranslation",
                        verbose_name="Translation",
                    ),
                ),
            ],
            options={
                "verbose_name": "News URL",
                "verbose_name_plural": "News URLs",
            },
        ),
    ]
