- name: Create app secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: app-secret
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        DJANGO_SETTINGS_MODULE: configs.settings
        ACTU_DATABASE_HOST: "{{ openshift[openshift_env].database.host }}"
        ACTU_DATABASE_PORT: "{{ openshift[openshift_env].database.port }}"
        ACTU_DATABASE_NAME: "{{ openshift[openshift_env].database.name }}"
        ACTU_DATABASE_USER: "{{ openshift[openshift_env].database.user }}"
        ACTU_DATABASE_PASSWORD: "{{ openshift[openshift_env].database.password }}"
        ACTU_SECRET_KEY: "{{ openshift[openshift_env].secret }}"
        ACTU_DEBUG_MODE: "true"
        ACTU_TENANT_ID: "{{ openshift[openshift_env].auth.tenant_id }}"
        ACTU_OIDC_RP_CLIENT_ID: "{{ openshift[openshift_env].auth.client_id }}"
        ACTU_OIDC_RP_CLIENT_SECRET: "{{ openshift[openshift_env].auth.client_secret }}"
