# Generated by Django 5.2.13 on 2026-08-28 07:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalAuditLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "object_id",
                    models.CharField(max_length=255, verbose_name="Object ID"),
                ),
                (
                    "object_repr",
                    models.CharField(
                        default="Not defined",
                        max_length=500,
                        verbose_name="Object Name",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Date"
                    ),
                ),
                (
                    "user",
                    models.CharField(
                        default="System", max_length=500, verbose_name="User"
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                ("details", models.JSONField(default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="Object Type",
                    ),
                ),
            ],
            options={
                "verbose_name": "Global log",
                "verbose_name_plural": "Global Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="audit_g_created_at_idx"
                    ),
                    models.Index(
                        fields=["content_type", "object_id", "-created_at"],
                        name="audit_g_ct_obj_idx",
                    ),
                    models.Index(
                        fields=["user", "-created_at"], name="audit_g_user_idx"
                    ),
                ],
            },
        ),
    ]
