# Generated by Django 5.2.17 on 2026-09-18 08:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0003_make_format_and_thematics_required"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewsLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "language",
                    models.CharField(
                        choices=[
                            ("en", "English"),
                            ("fr", "French"),
                            ("de", "German"),
                            ("it", "Italian"),
                        ],
                        max_length=2,
                        verbose_name="Language",
                    ),
                ),
                ("link", models.URLField(max_length=512, verbose_name="Link")),
                (
                    "news",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="links",
                        to="news.news",
                        verbose_name="News",
                    ),
                ),
            ],
            options={
                "verbose_name": "News link",
                "verbose_name_plural": "News links",
            },
        ),
    ]
