# Generated by Django 5.2.17 on 2026-08-20 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("news", "0002_news_format"),
    ]

    operations = [
        migrations.CreateModel(
            name="Link",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("link", models.CharField(max_length=90, verbose_name="Link")),
                (
                    "news",
                    models.ForeignKey(
                        blank=True,
                        help_text="News related to this link.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="news",
                        to="news.news",
                        verbose_name="News",
                    ),
                ),
            ],
            options={
                "verbose_name": "Link",
                "verbose_name_plural": "Links",
            },
        ),
    ]
