- name: Create app secrets
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: "secret"
        namespace: "{{ openshift_namespace }}"
      type: Opaque
      stringData:
        DJANGO_SETTINGS_MODULE: configs.ocp
        ACTU_DATABASE_HOST: "{{ secrets.database.host }}"
        ACTU_DATABASE_NAME: "{{ secrets.database.name }}"
        ACTU_DATABASE_USER: "{{ secrets.database.user }}"
        ACTU_DATABASE_PASSWORD: "{{ secrets.database.password }}"
        ACTU_DATABASE_PORT: "{{ secrets.database.port }}"
        ACTU_SECRET_KEY: "{{ secrets.secret }}"
        ACTU_TENANT_ID: "{{ secrets.auth.tenant_id }}"
        ACTU_OIDC_RP_CLIENT_ID: "{{ secrets.auth.client_id }}"
        ACTU_OIDC_RP_CLIENT_SECRET: "{{ secrets.auth.client_secret }}"
        ACTU_API_USERNAME: "{{ secrets.epfl_api.username }}"
        ACTU_API_PASSWORD: "{{ secrets.epfl_api.password }}"
        ACTU_API_RIGHT_ID: "{{ secrets.epfl_api.right_id }}"
