- name: Create web Deployment
  kubernetes.core.k8s:
    definition:
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: "web"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "web"
          app.kubernetes.io/component: "web"
          app.kubernetes.io/managed-by: "ansible"
          app.kubernetes.io/name: "web"
          app.kubernetes.io/part-of: "web"
          app.kubernetes.io/version: "{{ app_image_tag }}"
          app.openshift.io/runtime: "django"
        annotations:
          app.openshift.io/vcs-uri: "https://github.com/epfl-si/actu"
      spec:
        replicas: 2
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxUnavailable: 1
        selector:
          matchLabels:
            app: "web"
        template:
          metadata:
            labels:
              app: "web"
          spec:
            affinity:
              podAntiAffinity:
                requiredDuringSchedulingIgnoredDuringExecution:
                  - labelSelector:
                      matchLabels:
                        app: "web"
                    topologyKey: kubernetes.io/hostname
                preferredDuringSchedulingIgnoredDuringExecution:
                  - weight: 100
                    podAffinityTerm:
                      labelSelector:
                        matchLabels:
                          app: "web"
                      topologyKey: topology.kubernetes.io/zone
            serviceAccountName: quay-image-pull-account
            containers:
              - image: "{{ quay_host }}/{{ quay_repo_name }}/{{ app_image }}"
                imagePullPolicy: Always
                name: "web"
                ports:
                  - containerPort: 8000
                    name: django-port
                envFrom:
                  - secretRef:
                      name: "secret"
                env:
                  - name: ACTU_DJANGO_EMAIL_BACKEND
                    value: "{{ django_email_backend }}"
                resources:
                  requests:
                    cpu: 10m
                    memory: 1Gi
                  limits:
                    memory: 1Gi
                readinessProbe:
                  httpGet:
                    path: /healthz/
                    port: 8000
                livenessProbe:
                  httpGet:
                    path: /healthz/
                    port: 8000
                volumeMounts:
                  - name: "web-volume"
                    mountPath: /public
                    subPath: public
            volumes:
              - name: "web-volume"
                persistentVolumeClaim:
                  claimName: "actu"

- name: Web-app - Service
  kubernetes.core.k8s:
    definition:
      apiVersion: v1
      kind: Service
      metadata:
        name: "web"
        namespace: "{{ openshift_namespace }}"
        labels:
          app: "web"
      spec:
        ports:
          - name: django
            port: 8000
        type: ClusterIP
        selector:
          app: "web"
