- name: opdo_secrets vars
  tags: always
  include_vars:
    file: "opdo-secrets-{{ 'test' if openshift_env == 'dev' else openshift_env }}.yml"
    name: opdo_secrets

- name: ConfigMap/opdo-ca
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: opdo-ca
        namespace: "{{ openshift_namespace }}"
      data:
        opdo-ca.crt: "{{ certificate }}"

- name: OPDo Secret
  kubernetes.core.k8s:
    state: present
    definitioneyaml_keys:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: opdo-logstash
        namespace: "{{ openshift_namespace }}"
      stringData:
        PIPELINE_OUTPUT_ELASTICSEARCH_HOST1: "{{ opdo_secrets.opdo.urls[0] }}"
        PIPELINE_OUTPUT_ELASTICSEARCH_HOST2: "{{ opdo_secrets.opdo.urls[1] }}"
        PIPELINE_OUTPUT_ELASTICSEARCH_HOST3: "{{ opdo_secrets.opdo.urls[2] | default('') }}"
        PIPELINE_OUTPUT_ELASTICSEARCH_INDEX: "{{ opdo_secrets.opdo.index }}"
        PIPELINE_OUTPUT_ELASTICSEARCH_API_KEY: "{{ opdo_secrets.opdo.api_key }}"
