- name: ConfigMap/opdo-ca
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: ConfigMap
      metadata:
        name: opdo-ca
        namespace: "{{ openshift_namespace }}"
      data:
        opdo-ca.crt: "{{ opdo_certificate }}"

- name: OPDo Secret
  kubernetes.core.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: Secret
      type: Opaque
      metadata:
        name: opdo-logstash
        namespace: "{{ openshift_namespace }}"
      stringData:
        PIPELINE_OUTPUT_ELASTICSEARCH_HOST1: "{{ secrets.opdo.urls[0] }}"
        PIPELINE_OUTPUT_ELASTICSEARCH_HOST2: "{{ secrets.opdo.urls[1] }}"
        PIPELINE_OUTPUT_ELASTICSEARCH_HOST3: "{{ secrets.opdo.urls[2] | default('') }}"
        PIPELINE_OUTPUT_ELASTICSEARCH_INDEX: "{{ secrets.opdo.index }}"
        PIPELINE_OUTPUT_ELASTICSEARCH_API_KEY: "{{ secrets.opdo.encoded }}"
