name: Test

on: [push, pull_request]

env:
  ACTU_SECRET_KEY: ${{ secrets.ACTU_SECRET_KEY }}
  ACTU_DATABASE_HOST: "postgres"
  ACTU_DATABASE_PORT: 5432
  ACTU_DATABASE_NAME: "actu"
  ACTU_DATABASE_USER: "actu"
  ACTU_DATABASE_PASSWORD: ${{ secrets.ACTU_DATABASE_PASSWORD }}
  ACTU_TENANT_ID: "UNUSED"
  ACTU_OIDC_RP_CLIENT_ID: "UNUSED"
  ACTU_OIDC_RP_CLIENT_SECRET: "UNUSED"

jobs:
  test:
    runs-on: ubuntu-latest
    name: Test

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Hadolint
        run: |
          make hadolint

      - name: Build/Start containers
        run: |
          docker compose -f docker-compose-dev.yml up -d
          sleep 10

      - name: Setup actu
        run: |
          docker compose -f docker-compose-dev.yml exec \
            -e DJANGO_SETTINGS_MODULE='configs.ci' django python src/manage.py compilemessages

      - name: Check migrations
        run: |
          docker compose -f docker-compose-dev.yml exec \
            django python src/manage.py makemigrations --check --dry-run

      - name: Check translations
        run: |
          docker compose -f docker-compose-dev.yml exec \
            -e DJANGO_SETTINGS_MODULE='configs.ci' django python src/manage.py makemessages -a --no-location --no-wrap
          git diff --numstat | awk '{if ($1>0 || $2>0) { exit 1 }}'

      - name: Black
        run: |
          docker compose -f docker-compose-dev.yml exec \
            django black --check --diff .

      - name: isort
        run: |
          docker compose -f docker-compose-dev.yml exec \
            django isort --check-only --diff .

      - name: Flake8
        run: |
          docker compose -f docker-compose-dev.yml exec \
            django flake8

      - name: Stylelint
        run: |
          docker compose -f docker-compose-dev.yml exec \
            assets npm run stylelint

      - name: Coverage
        run: |
          docker compose -f docker-compose-dev.yml exec \
            -e DJANGO_SETTINGS_MODULE='configs.ci' django coverage run src/manage.py test
          docker compose -f docker-compose-dev.yml exec \
            django coverage xml
          docker cp local-django-actu:/app/coverage.xml .

      - name: Codecov
        uses: codecov/codecov-action@v7
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
